DROP DATABASE BANK_MANAGEMENT_SYSTEM;
 
CREATE DATABASE BANK_MANAGEMENT_SYSTEM;

USE BANK_MANAGEMENT_SYSTEM;

SHOW DATABASES;

-- CUSTOMER_PERSONAL_INFO

CREATE TABLE CUSTOMER_PERSONAL_INFO
(
	CUSTOMER_ID VARCHAR(5),
    CUSTOMER_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE,
    GUARDIAN_NAME VARCHAR(30),
    ADDRESS VARCHAR(50),
    CONTACT_NO BIGINT(10),
    MAIL_ID VARCHAR(30),
    GENDER CHAR(1),
    MARITAL_STATUS VARCHAR(10),
    IDENTIFICATION_DOC_TYPE VARCHAR(20),
    ID_DOC_NO VARCHAR(20),
    CITIZENSHIP VARCHAR(10),
    CONSTRAINT CUST_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID) 
);
SHOW TABLES;

-- CUSTOMER_REFERENCE_INFO

CREATE TABLE CUSTOMER_REFERENCE_INFO
(
	CUSTOMER_ID VARCHAR(5),
    REFERENCE_ACC_NAME VARCHAR(20),
    REFERENCE_ACC_NO BIGINT(16),
    REFERENCE_ACC_ADDRESS VARCHAR(50),
    RELATION VARCHAR(25),
    CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID),
    CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);
SHOW TABLES;

-- BANK_INFO

CREATE TABLE BANK_INFO
(
	IFSC_CODE VARCHAR(15),
    BANK_NAME VARCHAR(25),
    BRANCH_NAME VARCHAR(25),
    CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
);
SHOW TABLES;

-- ACCOUNT_HOLDER_INFO

CREATE TABLE ACCOUNT_HOLDER_INFO
(
	ACCOUNT_NO BIGINT(16),
    CUSTOMER_ID VARCHAR(5),
    ACCOUNT_TYPE VARCHAR(10),
    REGISTRATION_DATE DATE,
    ACTIVATION_DATE DATE,
    IFSC_CODE VARCHAR(10),
    INTEREST DECIMAL(7,2),
    INITIAL_DEPOSIT BIGINT(10),
    CONSTRAINT ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
    CONSTRAINT ACC_INFO_PERS_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);
SHOW TABLES;

-- CUSTOMER_PERSONAL_INFO VALUES

INSERT INTO CUSTOMER_PERSONAL_INFO VALUES(1001,'SAMRUDDHI KANGUDE','2003/06/01','SANDIP KANGUDE','PUNE MH',
'7218380003','samrudhikangude@gmail.com','FEMALE','NO','ID CARD','102345IDFC','PUNE');

INSERT INTO CUSTOMER_PERSONAL_INFO VALUES(2002,'SOHAM PAWAR','2003/11/03','SANTOSH PAWAR','BARAMATI MH',
'7030806080','sohampawar1030@gmail.com','MALE','NO','ID CARD','202345IDFC','BARAMATI');

INSERT INTO CUSTOMER_PERSONAL_INFO VALUES(3003,'ADITI MAGAR','2003/05/28','SHANKAR MAGAR','USMANABAD MH',
'7499415065','aditimagar6421@gmail.com','FEMALE','NO','ID CARD','102345IDFC','USMANABAD');

SELECT *FROM CUSTOMER_PERSONAL_INFO;

-- CUSTOMER_REFERENCE_INFO VALUES

INSERT INTO CUSTOMER_REFERENCE_INFO VALUES(1001,'SANDIP KANGUDE','123567438726','PUNE MH','FATHER');
INSERT INTO CUSTOMER_REFERENCE_INFO VALUES(2002,'SANTOSH PAWAR','456727938726','BARAMATI MH','FATHER');
INSERT INTO CUSTOMER_REFERENCE_INFO VALUES(3003,'SHANKAR MAGAR','687667438726','USMANABAD MH','FATHER');

SELECT *FROM CUSTOMER_REFERENCE_INFO;

-- BANK_INFO VALUES

INSERT INTO BANK_INFO VALUES('MAHA0012','BOM','PUNE KOTHRUD');
INSERT INTO BANK_INFO VALUES('SBIKN0123','SBI','BARAMATI WADGAON');
INSERT INTO BANK_INFO VALUES('ICIKP0232','ICICI','USMANABAD WAGHOLI');

SELECT *FROM BANK_INFO;

-- ACCOUNT_HOLDER_INFO VALUES

INSERT INTO ACCOUNT_HOLDER_INFO VALUES(986542456786,1001,'SAVING ACCOUNT','2007/07/23',
'2007/08/03','IFSC6789MH','7889',70000);

INSERT INTO ACCOUNT_HOLDER_INFO VALUES(754547656786,2002,'SAVING ACCOUNT','2011/09/05',
'2011/09/15','IFSC8943SBI','5631',90000);

INSERT INTO ACCOUNT_HOLDER_INFO VALUES(567432890011,3003,'SAVING ACCOUNT','2015/11/28',
'2015/12/08','IFSC0076ICICI','1049',400000);

SELECT *FROM ACCOUNT_HOLDER_INFO; 








 
    